#!/usr/bin/env node
// Regenerates accidents-data.generated.ts from all JSON files in apps/front/data/.
// Safe to run at any time; always reflects the current state of the data directory.

import { readdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = process.cwd()
const DATA_DIR = resolve(ROOT, 'apps/front/data')
const INDEX_FILE = resolve(
  ROOT,
  'apps/front/src/static/accidents-data.generated.ts',
)

export function generateIndex() {
  const allFiles = readdirSync(DATA_DIR)
    .filter((f) => f.endsWith('.json'))
    .sort()

  const lines = [
    '// AUTO-GENERATED FILE — do not edit by hand.',
    '// Regenerated by .github/workflows/case-submission.yml when a new case is submitted.',
    '',
  ]
  allFiles.forEach((file, i) => {
    lines.push(`import accident${i} from '../../data/${file}'`)
  })
  lines.push('')
  lines.push("import type { Accident } from './accidents'")
  lines.push('')
  lines.push('export const ACCIDENT_DATA: Accident[] = [')
  allFiles.forEach((_, i) => {
    lines.push(`  accident${i} as Accident,`)
  })
  lines.push(']')

  writeFileSync(INDEX_FILE, `${lines.join('\n')}\n`)
}

// Run directly when invoked as a script (not when imported as a module)
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  generateIndex()
}
