// AUTO-GENERATED FILE — do not edit by hand.
// Regenerated by .github/workflows/case-submission.yml when a new case is submitted.

import accident0 from '../../data/001-sk-telecom-usim-2025.json'
import accident1 from '../../data/002-테스트-중입니다-2026.json'
import accident2 from '../../data/003-테스트-2026.json'
import accident3 from '../../data/004-interpark-2016.json'
import accident4 from '../../data/005-auction-2008.json'
import accident5 from '../../data/006-card-3sa-2014.json'
import accident6 from '../../data/007-yeogi-eottae-2017.json'
import accident7 from '../../data/008-3-20-cyber-2013.json'
import accident8 from '../../data/009-11st-2021.json'
import accident9 from '../../data/010-goodata-2024.json'

import type { Accident } from './accidents'

export const ACCIDENT_DATA: Accident[] = [
  accident0 as Accident,
  accident1 as Accident,
  accident2 as Accident,
  accident3 as Accident,
  accident4 as Accident,
  accident5 as Accident,
  accident6 as Accident,
  accident7 as Accident,
  accident8 as Accident,
  accident9 as Accident,
]
