// AUTO-GENERATED FILE — do not edit by hand.
// Regenerated by .github/workflows/case-submission.yml when a new case is submitted.

import accident0 from '../../data/073ea6d3-0ea9-424c-a026-b525dd9cf7be.json'
import accident1 from '../../data/210fba9e-936a-45a5-8bd6-f6e5baf8e4e7.json'
import accident2 from '../../data/67050736-cc5b-4955-a5d6-28157e1eaf4f.json'
import accident3 from '../../data/67fcc242-f755-4c2c-bc9e-0ca952e1edb2.json'
import accident4 from '../../data/701994cf-6327-4a39-9bba-2777a479fe8e.json'
import accident5 from '../../data/8870baf6-a1b2-4589-af16-b402da248ae6.json'
import accident6 from '../../data/a01de281-92f3-4868-8415-9c12a1acfb0e.json'
import accident7 from '../../data/c7fac9c5-898e-4219-8420-d4d29dcefa02.json'
import accident8 from '../../data/e0e87a0d-39ce-46c7-bb79-ba2e023c0431.json'

import type { Accident } from './accidents'

export const ACCIDENT_DATA: Accident[] = [
  accident0 as Accident,
  accident1 as Accident,
  accident2 as Accident,
  accident3 as Accident,
  accident4 as Accident,
  accident5 as Accident,
  accident6 as Accident,
  accident7 as Accident,
  accident8 as Accident,
]
