// AUTO-GENERATED FILE — do not edit by hand.
// Regenerated by .github/workflows/case-submission.yml when a new case is submitted.

import accident001 from '../../data/001-sk-telecom-usim-2025.json'
import accident002 from '../../data/002-kt-2014.json'
import accident003 from '../../data/003-lg-uplus-2023.json'
import accident004 from '../../data/004-interpark-2016.json'
import accident005 from '../../data/005-auction-2008.json'
import accident006 from '../../data/006-card-3sa-2014.json'
import accident007 from '../../data/007-yeogi-eottae-2017.json'
import accident008 from '../../data/008-3-20-cyber-2013.json'
import accident009 from '../../data/009-11st-2021.json'
import accident010 from '../../data/010-goodata-2024.json'
import type { Accident } from './accidents'

export const ACCIDENT_DATA: Accident[] = [
  accident001 as Accident,
  accident002 as Accident,
  accident003 as Accident,
  accident004 as Accident,
  accident005 as Accident,
  accident006 as Accident,
  accident007 as Accident,
  accident008 as Accident,
  accident009 as Accident,
  accident010 as Accident,
]
